baseURL: "https://5y3datif.github.io/atif.github.io/" 
title: Dr. Syed Muhammad Atif
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Curriculum Vitae
          url: cv.pdf
          weight: 2
        - name: Contact Me
          url: officehours/
          weight: 3

params:
    description: "With a background in computer science and software engineering, I am currently serving as an Assistant Professor at the Sir Syed University of Engineering and Technology, Karachi, Pakistan."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Syed Muhammad Atif
          subtitle: "With a background in computer science and software engineering."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dr. Syed Muhammad Atif
          buttons:
            - name: Publications
              url: papers/
            - name: Curriculum Vitae
              url: cv.pdf
            - name: Contact Me
              url: officehours/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:syed.muhammad.atif@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=FHaMgJkAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/5y3datif
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dr. Syed Muhammad Atif"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
