baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Syed Muhammad Atif
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "With a background in computer science and software engineering, I am currently serving as an Assistant Professor at the Sir Syed University of Engineering and Technology, Karachi, Pakistan."
    author: Syed Muhammad Atif
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Syed Muhammad Atif
          subtitle: "With a background in computer science and software engineering, I am currently serving as an Assistant Professor 
          at Sir Syed University of Engineering and Technology (SSUET), Karachi, Pakistan. Before joining SSUET, I have served as 
          Assistant Professor at the Ziauddin University in Karachi, Pakistan for two years. Prior to joining Ziauddin University, 
          I held the position of Senior AI Developer at HetroCloud, a research project funded by 
          the National Center of Big Data and Cloud Computing (NCBC) that was executed at the Karachi Institute of Economics and Technology (KIET). 
          My expertise in machine learning and computer vision spans over five years, and I have contributed to several peer‑reviewed articles 
          published in renowned conferences and journals such as Elsevier Pattern Recognition Letters, Elsevier 
          Computer Networks, Springer Neural Processing Letters, IEEE Access, KSII Transactions on Internet and Information 
          Systems, and IEEE TENCON. In 2017, I received the HEC Indigenous Ph.D. Fellowship in recognition of my academic 
          achievements to pursue doctoral studies. My research interests lie in Matrix Factorization, Network Tomography, 
          ill‑posed problems, radial basis function neural networks, computer vision and deep learning. Additionally, I have 
          served as a reviewer for the Elsevier journals Computer Networks and Results in Control and Optimization."
          imageUrl: "atif.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: papers/
            - name: Curriculum Vitae
              url: cv.pdf
            - name: Contact Me
              url: officehours/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:syed.muhammad.atif@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=FHaMgJkAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/5y3datif
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
